---
consul:
    version: 1.17.0-1
    service:
        user: consul
    storage:
        data: /data/consul
        config: /etc/consul.d
        log: /var/log/consul
        ssl: /etc/consul/ssl
    config:
        port:
            grpc: 8502
            grpc_tls: 8503
            serf: 8301
            dns: 8600
        dc: 1
...
